# Parameters
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 25
CLASSES: 4
WEIGHTS: 'IMAGENET1K_V1'
LEARNING_RATE: 0.01
EARLY_STOPPING_PATIENCE: 5
RANDOM_STATE: 42