artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1EAlEHx68JBGW0PjF4PiOoXF4acsSClI4/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  extracted_data: artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pt


training:
  root_dir: artifacts/training
  last_model_path: artifacts/training/last_model.pth
  best_model_path: artifacts/training/best_model.pth

evaluation:
  mlflow_uri: 'https://dagshub.com/GorkemKola/kidney-disease-classification.mlflow'

prediction:
  root_dir: artifacts/prediction